[book]
authors = ["Trevor Barnes"]
language = "en"
src = "src"
title = "ML for Spacepower Simulations"

[output.html]
mathjax-support = true
fold.enable = true
level = 0 

[preprocessor.quiz]
[preprocessor.repl]
python.enable = true