[book]
authors = ["Trevor Barnes"]
language = "en"
src = "src"
title = "ML for Spacepower Simulations"

[output.html]
fold.enable = true
level = 0

[preprocessor.toc]
command = "mdbook-toc"

[preprocessor.quiz]
[preprocessor.repl]
python.enable = true

[preprocessor.katex]
block-delimiter = { left = "\\[", right = "\\]" }
inline-delimiter = { left = "\\(", right = "\\)" }